export { default as Categories } from './Categories'
export { default as Dashboard } from './Dashboard'
export { default as NotFound } from './NotFound'
export { default as Orders } from './Orders'
export { default as Products } from './Products'
export { default as Users } from './Users'
